---
# Handler para actualizar la dirección del servidor en kubeconfig
- name: Actualizar servidor en kubeconfig
  replace:
    path: "/home/{{ cluster_user }}/.kube/config"
    regexp: 'https://127.0.0.1:6443'
    replace: "https://{{ vip_address }}:6443"

# Handler para reiniciar el servicio k3s
- name: Reiniciar k3s
  systemd:
    name: k3s
    state: restarted
